version: '3'

services:
  python:
    restart: always
    build: .
    container_name: 'py3-container'
    working_dir: '/var/docker-python'
    tty: true
    volumes:
      - ./app:/var/docker-python/app