version: '3'

services:
  python:
    restart: always
    build: .
    working_dir: '/var/docker-python'
    tty: true
    volumes:
      - ./app:/var/docker-python/app
    environment:
      - SCRAPING_URL=${SCRAPING_URL}
